<a href="https://colab.research.google.com/github/tasdid25/Spam-Email-Filtering-with-Naive-Bayes/blob/main/Spam_Text_Filtering_with_Naive_Bayes_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2 align='center'>NLP: Text Representation - Bag Of Words (BOW)</h2>

In [32]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv("spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [34]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [35]:
df.shape

(5572, 2)

In [36]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

# <h3>Train test split</h3>

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Category, test_size=0.2, random_state=1)

In [38]:
X_train.shape

(4457,)

In [39]:
X_test.shape

(1115,)

In [40]:
X_test

1078                         Yep, by the pretty sculpture
4028        Yes, princess. Are you going to make me moan?
958                            Welp apparently he retired
4642                                              Havent.
4674    I forgot 2 ask ü all smth.. There's a card on ...
                              ...                        
324     That would be great. We'll be at the Guild. Co...
1163    Free entry in 2 a wkly comp to win FA Cup fina...
86      For real when u getting on yo? I only need 2 m...
4214                     I attended but nothing is there.
90      Yeah do! Don‘t stand to close tho- you‘ll catc...
Name: Message, Length: 1115, dtype: object

In [41]:
X_train

1642    Hi , where are you? We're at  and they're not ...
2899          If you r @ home then come down within 5 min
480     When're you guys getting back? G said you were...
3485    Tell my  bad character which u Dnt lik in me. ...
157                           I'm leaving my house now...
                              ...                        
905     We're all getting worried over here, derek and...
5192    Oh oh... Den muz change plan liao... Go back h...
3980    CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235     Text & meet someone sexy today. U can find a d...
5157                              K k:) sms chat with me.
Name: Message, Length: 4457, dtype: object

In [42]:
X_train[:4]

1642    Hi , where are you? We're at  and they're not ...
2899          If you r @ home then come down within 5 min
480     When're you guys getting back? G said you were...
3485    Tell my  bad character which u Dnt lik in me. ...
Name: Message, dtype: object

In [43]:
type(y_train)

pandas.core.series.Series

In [44]:
y_train[:4]

1642    ham
2899    ham
480     ham
3485    ham
Name: Category, dtype: object

In [45]:
X_train.values

array(["Hi , where are you? We're at  and they're not keen to go out i kind of am but feel i shouldn't so can we go out tomo, don't mind do you?",
       'If you r @ home then come down within 5 min',
       "When're you guys getting back? G said you were thinking about not staying for mcr",
       ...,
       'CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C YA 2MORO! WHO NEEDS BLOKES',
       'Text & meet someone sexy today. U can find a date or even flirt its up to U. Join 4 just 10p. REPLY with NAME & AGE eg Sam 25. 18 -msg recd@thirtyeight pence',
       'K k:) sms chat with me.'], dtype=object)

In [46]:
X_train.values.shape

(4457,)

In [47]:
type(X_train.values)

numpy.ndarray

# <h3>Create bag of words representation using CountVectorizer</h3>

In [48]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

In [49]:
emails = [
            'Upto 20% discount reward!',
            'Hey mohan, discount Upto'
         ]

emails_cv = v.fit_transform(emails)
emails_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (2, 6)>

In [50]:
emails_cv.toarray()

array([[1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 1]])

In [51]:
v.get_feature_names_out()

array(['20', 'discount', 'hey', 'mohan', 'reward', 'upto'], dtype=object)

In [52]:
pd.DataFrame(emails_cv.toarray(), columns=v.get_feature_names_out())

20  discount  hey  mohan  reward  upto
0   1         1    0      0       1     1
1   0         1    1      1       0     1

In [53]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58978 stored elements and shape (4457, 7711)>

In [54]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [55]:
X_train_cv.shape

(4457, 7711)

In [56]:
X_train_cv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [57]:
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zyada', 'èn', '〨ud'],
      dtype=object)

In [58]:
pd.DataFrame(X_train_cv.toarray(), columns=v.get_feature_names_out())

00  000  008704050406  0121  01223585236  01223585334  0125698789  02  \
0      0    0             0     0            0            0           0   0   
1      0    0             0     0            0            0           0   0   
2      0    0             0     0            0            0           0   0   
3      0    0             0     0            0            0           0   0   
4      0    0             0     0            0            0           0   0   
...   ..  ...           ...   ...          ...          ...         ...  ..   
4452   0    0             0     0            0            0           0   0   
4453   0    0             0     0            0            0           0   0   
4454   0    0             0     0            0            0           0   0   
4455   0    0             0     0            0            0           0   0   
4456   0    0             0     0            0            0           0   0   

      0207  02072069400  ...  zed  zeros  zhong  zindgi  zoe  zoom  zouk  \
0        0            0  ...    0      0      0       0    0     0     0   
1        0            0  ...    0      0      0       0    0     0     0   
2        0            0  ...    0      0      0       0    0     0     0   
3        0            0  ...    0      0      0       0    0     0     0   
4        0            0  ...    0      0      0       0    0     0     0   
...    ...          ...  ...  ...    ...    ...     ...  ...   ...   ...   
4452     0            0  ...    0      0      0       0    0     0     0   
4453     0            0  ...    0      0      0       0    0     0     0   
4454     0            0  ...    0      0      0       0    0     0     0   
4455     0            0  ...    0      0      0       0    0     0     0   
4456     0            0  ...    0      0      0       0    0     0     0   

      zyada  èn  〨ud  
0         0   0    0  
1         0   0    0  
2         0   0    0  
3         0   0    0  
4         0   0    0  
...     ...  ..  ...  
4452      0   0    0  
4453      0   0    0  
4454      0   0    0  
4455      0   0    0  
4456      0   0    0  

[4457 rows x 7711 columns]

In [74]:
# Display 10 words from the vocabulary
list(v.vocabulary_.items())[:10]

[('hi', 3423),
 ('where', 7442),
 ('are', 1051),
 ('you', 7674),
 ('we', 7370),
 ('re', 5564),
 ('at', 1119),
 ('and', 963),
 ('they', 6794),
 ('not', 4813)]

In [60]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [61]:
np.where(X_train_np[0]!=0)

(array([ 937,  963, 1051, 1119, 1578, 1632, 2377, 2408, 2795, 3153, 3423,
        3906, 3940, 4474, 4813, 4872, 4985, 5564, 6077, 6230, 6794, 6889,
        6910, 7370, 7442, 7674]),)

In [62]:
X_train_np[0][1771]

np.int64(0)

# <h3>Train the naive bayes model</h3>

In [63]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

# <h3>Evaluate Performance</h3>

In [64]:
X_test_cv = v.transform(X_test)

In [65]:
X_test_cv.toarray().shape

(1115, 7711)

In [66]:
model.score(X_test_cv, y_test)

0.989237668161435

In [67]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99       968
        spam       0.98      0.94      0.96       147

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [68]:
emails = [
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'Hey mohan, can we get together to watch footbal game tomorrow?'
]

In [69]:
emails_count = v.transform(emails)
emails_count.toarray().shape

(2, 7711)

In [70]:
#emails_count.toarray().shape
model.predict(emails_count)

array(['spam', 'ham'], dtype='<U4')

# <h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [71]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [72]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [73]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99       968
        spam       0.98      0.94      0.96       147

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

