<h2 align='center'>NLP: Text Representation - Bag Of Words (BOW)</h2>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df.shape

(5572, 2)

In [ ]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

<h3>Train test split</h3>

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Category, test_size=0.2, random_state=1)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
X_test

In [ ]:
X_train

1642    Hi , where are you? We're at  and they're not ...
2899          If you r @ home then come down within 5 min
480     When're you guys getting back? G said you were...
3485    Tell my  bad character which u Dnt lik in me. ...
157                           I'm leaving my house now...
                              ...                        
905     We're all getting worried over here, derek and...
5192    Oh oh... Den muz change plan liao... Go back h...
3980    CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235     Text & meet someone sexy today. U can find a d...
5157                              K k:) sms chat with me.
Name: Message, Length: 4457, dtype: object

In [ ]:
X_train[:4]

1642    Hi , where are you? We're at  and they're not ...
2899          If you r @ home then come down within 5 min
480     When're you guys getting back? G said you were...
3485    Tell my  bad character which u Dnt lik in me. ...
Name: Message, dtype: object

In [ ]:
type(y_train)

pandas.core.series.Series

In [ ]:
y_train[:4]

1642    ham
2899    ham
480     ham
3485    ham
Name: Category, dtype: object

In [ ]:
X_train.values

array(["Hi , where are you? We're at  and they're not keen to go out i kind of am but feel i shouldn't so can we go out tomo, don't mind do you?",
       'If you r @ home then come down within 5 min',
       "When're you guys getting back? G said you were thinking about not staying for mcr",
       ...,
       'CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C YA 2MORO! WHO NEEDS BLOKES',
       'Text & meet someone sexy today. U can find a date or even flirt its up to U. Join 4 just 10p. REPLY with NAME & AGE eg Sam 25. 18 -msg recd@thirtyeight pence',
       'K k:) sms chat with me.'], dtype=object)

In [ ]:
X_train.values.shape

In [ ]:
type(X_train.values)

<h3>Create bag of words representation using CountVectorizer</h3>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

In [ ]:
emails = [
            'Upto 20% discount reward!',
            'Hey mohan, discount Upto'
         ]

emails_cv = v.fit_transform(emails)
emails_cv

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
emails_cv.toarray()

array([[1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 1]], dtype=int64)

In [ ]:
v.get_feature_names_out()

array(['20', 'discount', 'hey', 'mohan', 'reward', 'upto'], dtype=object)

In [ ]:
pd.DataFrame(emails_cv.toarray(), columns=v.get_feature_names_out())

20  discount  hey  mohan  reward  upto
0   1         1    0      0       1     1
1   0         1    1      1       0     1

In [ ]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7711 sparse matrix of type '<class 'numpy.int64'>'
	with 58978 stored elements in Compressed Sparse Row format>

In [ ]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
X_train_cv.shape

(4457, 7711)

In [ ]:
X_train_cv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zyada', 'èn', '〨ud'],
      dtype=object)

In [ ]:
pd.DataFrame(X_train_cv.toarray(), columns=v.get_feature_names_out())

00  000  008704050406  0121  01223585236  01223585334  0125698789  02  \
0      0    0             0     0            0            0           0   0   
1      0    0             0     0            0            0           0   0   
2      0    0             0     0            0            0           0   0   
3      0    0             0     0            0            0           0   0   
4      0    0             0     0            0            0           0   0   
...   ..  ...           ...   ...          ...          ...         ...  ..   
4452   0    0             0     0            0            0           0   0   
4453   0    0             0     0            0            0           0   0   
4454   0    0             0     0            0            0           0   0   
4455   0    0             0     0            0            0           0   0   
4456   0    0             0     0            0            0           0   0   

      0207  02072069400  ...  zed  zeros  zhong  zindgi  zoe  zoom  zouk  \
0        0            0  ...    0      0      0       0    0     0     0   
1        0            0  ...    0      0      0       0    0     0     0   
2        0            0  ...    0      0      0       0    0     0     0   
3        0            0  ...    0      0      0       0    0     0     0   
4        0            0  ...    0      0      0       0    0     0     0   
...    ...          ...  ...  ...    ...    ...     ...  ...   ...   ...   
4452     0            0  ...    0      0      0       0    0     0     0   
4453     0            0  ...    0      0      0       0    0     0     0   
4454     0            0  ...    0      0      0       0    0     0     0   
4455     0            0  ...    0      0      0       0    0     0     0   
4456     0            0  ...    0      0      0       0    0     0     0   

      zyada  èn  〨ud  
0         0   0    0  
1         0   0    0  
2         0   0    0  
3         0   0    0  
4         0   0    0  
...     ...  ..  ...  
4452      0   0    0  
4453      0   0    0  
4454      0   0    0  
4455      0   0    0  
4456      0   0    0  

[4457 rows x 7711 columns]

In [ ]:
v.vocabulary_

{'hi': 3423,
 'where': 7442,
 'are': 1051,
 'you': 7674,
 'we': 7370,
 're': 5564,
 'at': 1119,
 'and': 963,
 'they': 6794,
 'not': 4813,
 'keen': 3906,
 'to': 6889,
 'go': 3153,
 'out': 4985,
 'kind': 3940,
 'of': 4872,
 'am': 937,
 'but': 1578,
 'feel': 2795,
 'shouldn': 6077,
 'so': 6230,
 'can': 1632,
 'tomo': 6910,
 'don': 2408,
 'mind': 4474,
 'do': 2377,
 'if': 3593,
 'home': 3469,
 'then': 6782,
 'come': 1908,
 'down': 2433,
 'within': 7511,
 'min': 4471,
 'when': 7438,
 'guys': 3278,
 'getting': 3116,
 'back': 1196,
 'said': 5845,
 'were': 7419,
 'thinking': 6804,
 'about': 759,
 'staying': 6408,
 'for': 2927,
 'mcr': 4392,
 'tell': 6710,
 'my': 4650,
 'bad': 1199,
 'character': 1738,
 'which': 7448,
 'dnt': 2376,
 'lik': 4108,
 'in': 3633,
 'me': 4393,
 'll': 4156,
 'try': 7007,
 'change': 1730,
 'lt': 4243,
 'gt': 3254,
 'add': 813,
 'tat': 6671,
 'new': 4743,
 'year': 7650,
 'resolution': 5708,
 'waiting': 7308,
 'ur': 7147,
 'reply': 5688,
 'be': 1270,
 'frank': 2963,
 'go

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
np.where(X_train_np[0]!=0)

In [ ]:
X_train_np[0][1771]

<h3>Train the naive bayes model</h3>

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

<h3>Evaluate Performance</h3>

In [ ]:
X_test_cv = v.transform(X_test)

In [ ]:
X_test_cv.toarray().shape

(1115, 7711)

In [ ]:
model.score(X_test_cv, y_test)

0.989237668161435

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

In [ ]:
emails = [
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'Hey mohan, can we get together to watch footbal game tomorrow?'
]

In [ ]:
emails_count = v.transform(emails)
emails_count.toarray().shape

(2, 7711)

In [ ]:
#emails_count.toarray().shape
model.predict(emails_count)

array(['spam', 'ham'], dtype='<U4')

<h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

In [ ]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))